version: '3.4'
x-common-variables: &common-variables
  SERVERFULL_RUNTIME_LOGGER_OUTPUT: "STDOUT"
  SERVERFULL_RUNTIME_LOGGER_LEVEL: "INFO"
  SERVERFULL_RUNTIME_STATS_OUTPUT: "NULL"
  SERVERFULL_RUNTIME_STATS_DATADOG_TAGS: ""
  SERVERFULL_RUNTIME_STATS_DATADOG_PACKETSIZE: 32768
  SERVERFULL_RUNTIME_STATS_DATADOG_FLUSHINTERVAL: 10s
  SERVERFULL_RUNTIME_STATS_DATADOG_ADDRESS: statsd:8125
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *common-variables
      SERVERFULL_RUNTIME_HTTPSERVER_ADDRESS: :8081
      SERVERFULL_RUNTIME_CONNSTATE_REPORTINTERVAL: 5s
      SERVERFULL_RUNTIME_CONNSTATE_HIJACKEDCOUNTER: http.server.connstate.hijacked
      SERVERFULL_RUNTIME_CONNSTATE_CLOSEDCOUNTER: http.server.connstate.closed
      SERVERFULL_RUNTIME_CONNSTATE_IDLEGAUGE: http.server.connstate.idle.gauge
      SERVERFULL_RUNTIME_CONNSTATE_IDLECOUNTER: http.server.connstate.idle
      SERVERFULL_RUNTIME_CONNSTATE_ACTIVEGAUGE: http.server.connstate.active.gauge
      SERVERFULL_RUNTIME_CONNSTATE_ACTIVECOUNTER: http.server.connstate.active
      SERVERFULL_RUNTIME_CONNSTATE_NEWGAUGE: http.server.connstate.new.gauge
      SERVERFULL_RUNTIME_CONNSTATE_NEWCOUNTER: http.server.connstate.new
      SERVERFULL_RUNTIME_SIGNALS_INSTALLED: OS
      SERVERFULL_RUNTIME_SIGNALS_OS_SIGNALS: 15 2
      NEXPOSEVULNFILTER_LAMBDAMODE: "false"
      NEXPOSEVULNFILTER_PRODUCER_TYPE: "POST"
      NEXPOSEVULNFILTER_PRODUCER_POST_ENDPOINT: "http://gateway-outgoing:8082/publish"
      NEXPOSEVULNFILTER_PRODUCER_POST_HTTPCLIENT_TYPE: "DEFAULT"
      NEXPOSEVULNFILTER_PRODUCER_POST_HTTPCLIENT_SMART_OPENAPI: ""
      NEXPOSEVULNFILTER_VULNERABILITYFILTER_CVSSV2MINIMUMSCORE: 7.0
      NEXPOSEVULNFILTER_VULNERABILITYFILTER_VULNIDREGEXMATCH: tls-server-cert.*expire.*|ssl-.*sign.*
      NEXPOSEVULNFILTER_VULNERABILITYFILTER_ALLOWALLLOCALCHECKS: "true"

  gateway-incoming:
    build:
      context: .
      dockerfile: gateway-incoming.Dockerfile
    ports:
      - "8080:8080"
    environment:
      <<: *common-variables
  gateway-outgoing:
    build:
      context: .
      dockerfile: gateway-outgoing.Dockerfile
    ports:
      - "8082:8082"
    environment:
      <<: *common-variables
      PORTS_GATEWAY_OUTGOING: "8082"
      HTTPPRODUCER_API_HOST: ""
