# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "github.com/asecurityteam/settings"
  version = "^0.1.0"

[[constraint]]
  name = "github.com/asecurityteam/serverfull"
  version = "^0.4.0"

[[constraint]]
  name = "github.com/asecurityteam/component-producer"
  version = "^0.4.0"

[[override]]
  name = "github.com/Jeffail/gabs"
  version = "v1.3.0"

[[override]]
  name = "github.com/asecurityteam/runhttp"
  version = "^0.2.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.8.1"

